
version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: gg-nexus-mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  
    environment:
      MONGO_INITDB_DATABASE: gg_nexus

volumes:
  mongo_data: